### ISSUE TITLE
git install error

### ISSUE THREAD

**Issue by CureSaba** [shirowanisan/tsukuyomichan-talksoft#6]
pipを実行するとエラーが出ます。
使用環境
OS：Windows11
CPU：Ryzen9 5950x
GPU：RTX 3080ti
メモリー：32GB
Pythonバージョン：Python 3.10.5

以下logです
[log.txt](https://github.com/shirowanisan/tsukuyomichan-talksoft/files/9075621/log.txt)

**Comment by ActCelely** [comment]
私も同じエラーでますね....

**Comment by shirowanisan** [comment]
READMEにも記載しておりますが、Windows対応はしておりません。
よろしくお願いします。

**Comment by ActCelely** [comment]
なるほど、
見落としてしまいました。
すみません。

ですが、できないことはないんですか？
READMEには難易度が高いができると書いてあります。

**Comment by shirowanisan** [comment]
依存パッケージのバージョンを変えたり、エラーを解消すればイントールできる可能性はあります。
ですが、今は本コードの保守はしておらず、私からのサポートもしておりませんので、ご了承ください。

**Comment by ActCelely** [comment]
わかりました。
ありがとうございます！
